### PR TITLE
Support for Alerts

### PR DESCRIPTION
**Pull request by elblivion**
Hi @henrikhodne, this isn't 100% complete - I still want to take a look at associating/removing services to/from alerts - but if you have the time to cast some eyeballs at it I'd be very grateful. In any case I'll ping you when I think it's ready for review.

Not sure how to test this code (the API supported so far doesn't seem tested) - do you think it's enough that the acceptance tests in the Terraform provider cover this?

Thanks!

### CODE REVIEW

**Comment by henrikhodne** [comment]
I'll try to give this a review today or tomorrow, but I'm out traveling through Sunday so I might not be able to look into it until Monday.

For testing, I'd say acceptance tests in the Terraform provider is probably good for now. I feel like most of the code in this library isn't doing a lot, so there's not a whole lot to test. The only way to test API wrappers in my opinion is integration tests, so I need to spend some time to set that up before we have that working.

**Comment by henrikhodne** [comment]
This all looks good so far, let me know when you feel like it's ready to be merged and I'll look over it again.

**Comment by elblivion** [comment]
While doing work to extend the Terraform plugin for alerts I've realised I will also need to implement Services (the notifications part), I'll get back to you once that's ready.

**Comment by elblivion** [comment]
OK, I think this is ready for a final look :-)

I didn't really know any other way, so to use this in my fork of Terraform I changed the relevant files to point at my fork of this repo. So if I open a PR to Terraform without those changes the build will fail. Would you like to see the Terraform code before merging this, or shall I open that PR once this is merged?

**Comment by henrikhodne** [comment]
This looks great, I squashed the commits and merged into `master`.

**Pull request closed without merging**
