### PR TITLE
Add support for creating Annotations

### PR DESCRIPTION
**Pull request by elblivion**
https://www.librato.com/docs/api/#create-an-annotation

image

### CODE REVIEW

**Comment by elblivion** [comment]
👋  any comments/recommendations on this? Thanks!

**Comment by wchrisjohnson** [comment]
@elblivion I've been reviewing the [Librato API here ](https://www.librato.com/docs/api/#annotations) and it doesn't really match up to your initial effort. It specifically draws a distinction between an [Annotation Stream](https://www.librato.com/docs/api/#annotation-streams) vs 1-n [Annotation Events](https://www.librato.com/docs/api/#annotation-events). In reviewing your code, it looks like you might be confusing the two.

You could be assuming that Annotation Streams already exist, and are intending to only create Annotation Events. If so, I still think the `struct` for Annotation Event isn't quite right.

Please correct me if my understanding isn't correct!  😀

**Comment by elblivion** [comment]
Hi @wchrisjohnson ! 

We use annotations already with cURL in the Chef-based deployment automation we are working to replace.

You do not actually need to create a Stream, as per https://www.librato.com/docs/api/#create-an-annotation:

> If the annotation stream does not exist, it will be created automatically.

It sounds lazy and probably is, but makes life easier for us - we just need to POST events to the stream. Does that make sense? The annotation in the screenshot above was created with this code in a test account without any prior streams.

**Comment by elblivion** [comment]
The struct is missing the optional `start_time` and `end_time` fields - we currently don't use them! I could look at adding them though.

**Comment by wchrisjohnson** [comment]
@elblivion thanks for clarifying the auto-create of annotation streams; I'm good with leaving that for now, especially since you have it working. 

I would like to properly fill out that structvwith those two time fields. Once that's done, I'm ok with merging this PR, unless something changes.

**Comment by elblivion** [comment]
Hi @wchrisjohnson, added the missing fields.

**Comment by wchrisjohnson** [comment]
+1 lgtm

**Comment by elblivion** [comment]
Hm, something seems up with Travis build status updates. :-/ https://travis-ci.org/henrikhodne/go-librato/builds/251525187

**Comment by henrikhodne** [comment]
> Hm, something seems up with Travis build status updates. :-/ https://travis-ci.org/henrikhodne/go-librato/builds/251525187

Oops, that was my fault. Was cleaning up some OAuth autorizations on my GitHub account and went a bit overboard.

**Comment by henrikhodne** [comment]
Hmm, looks like it's not updating still, going to ping Travis support about it.

**Pull request merged**
